// Auto-generated by generate-routes script
export const RECIPE_MAPPING = {
  "bread": [
    "rye"
  ],
  "cookies": [
    "chocolate-chip",
    "hamantaschen"
  ],
  "grill": [
    "burgers",
    "chicken-thighs",
    "potatoes"
  ],
  "ice-cream": [],
  "meat": [
    "burgers",
    "chicken-breasts",
    "chicken-thighs",
    "salmon",
    "steak"
  ],
  "soup": [
    "chili"
  ]
};
