// Auto-generated by generate-routes script
export const RECIPE_MAPPING = {
  "bread": [
    "banana-bread",
    "challah",
    "cornbread",
    "french",
    "rye"
  ],
  "cookies": [
    "banana-oatmeal-chocolate-chip",
    "chocolate-chip",
    "hamantaschen",
    "m-&-m"
  ],
  "grill": [
    "burgers",
    "chicken-thighs",
    "potatoes"
  ],
  "ice-cream": [
    "vanilla"
  ],
  "meat": [
    "burgers",
    "chicken-breasts",
    "chicken-thighs",
    "salmon",
    "steak",
    "turkey-roast"
  ],
  "muffins": [],
  "sandwich": [
    "grilled-cheese"
  ],
  "soup": [
    "chili"
  ]
};
