// Auto-generated by generate-routes script
export const RECIPE_MAPPING = {
  "bread": [
    "banana-bread",
    "challah",
    "cornbread",
    "french",
    "rye"
  ],
  "cookies": [
    "chocolate-chip",
    "hamantaschen",
    "m-&-m"
  ],
  "grill": [
    "burgers",
    "chicken-thighs",
    "potatoes"
  ],
  "ice-cream": [],
  "meat": [
    "burgers",
    "chicken-breasts",
    "chicken-thighs",
    "salmon",
    "steak"
  ],
  "sandwich": [
    "grilled-cheese"
  ],
  "soup": [
    "chili"
  ]
};
