import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const recipesDir = path.join(__dirname, '../src/assets/recipes');
const outputFile = path.join(__dirname, '../src/utils/RecipeMapping.ts');

try {
    const recipeMapping = {};

    // Read all directories in the recipes folder
    const categories = fs.readdirSync(recipesDir, { withFileTypes: true });

    categories.forEach((category) => {
        if (category.isDirectory()) {
            const categoryPath = path.join(recipesDir, category.name);
            const recipes = fs.readdirSync(categoryPath)
                .filter((file) => file.endsWith('.md'))
                .map((file) => file.replace('.md', ''));

            recipeMapping[category.name] = recipes;
        }
    });

    // Generate TypeScript file
    const tsContent = `// Auto-generated by generate-routes script
export const RECIPE_MAPPING = ${JSON.stringify(recipeMapping, null, 2)};
`;

    fs.writeFileSync(outputFile, tsContent);
    console.log(`✓ Recipe mapping generated at ${outputFile}`);
    console.log(`Mapping: ${JSON.stringify(recipeMapping, null, 2)}`);
} catch (error) {
    console.error('Error generating recipe mapping:', error.message);
    process.exit(1);
}
